version: "3.8"
services:
  backend:
    build:
      context: ./backend/
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    command: npm run dev
